# jwt configuration for development
# Don't use for this production
# Don't contain production config

spring:
  mustache:
    suffix: .html

  # database config
  datasource:
    url: jdbc:h2:tcp://localhost/~/database
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.transaction: TRACE
    org.springframework.orm: TRACE
    com.dailywriting.web: debug
app:
  jwt:
    secret-key: q3t6w9z$C&F)J@NcRfUjXn2r5u7x!A%D
    expiration-seconds:  1209600