# jwt configuration for development
# Don't use for this production
# Don't contain production config

spring:
  mustache:
    suffix: .html

  # database config
  datasource:
    url: jdbc:h2:tcp://localhost/~/database
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

token:
  access:
    jwt-secret: development-secret
    expireInMs: 300000 # 5 minutes
  refresh:
    expireInMs: 1209600000 # 2 weeks


